<?php

namespace Jm\BalancedPaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Jm\BalancedPaymentBundle\Enum\PaymentStatusEnum;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function findByUserAndState($user, $state)
    {
        $query = $this->createQueryBuilder('p')
            ->where("p.state = :state")
            ->setParameter("state", $state)
            ->andWhere("p.fromUser = :user")
            ->setParameter("user", $user)
            ->getQuery()
        ;

        return $query->getResult();
    }

    public function findPending()
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.state = :state')
            ->setParameter('state', PaymentStatusEnum::PENDING)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
